config/routes.rb
Rails.application.routes.draw do

  resources :nadgodzinies
  post 'zmianas/index', to: 'zmianas#index'
  post 'zmianas/show'
  get 'zmianas/new'
  get 'zmianas/create'
  get 'zmianas/show'
  get 'zmianas/index'
  delete '/zmianas/destroy', to: 'zmianas#destroy'
  get '/zmianas/delete/', to: 'zmianas#destroy'

      resources :users do
          member do
              get :following, :followers
          end
      end
    resources :relationships,       only: [:create, :destroy]
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    
    post '/zmianas/destroy', to: 'zmianas#destroy'
    post '/zmianas', to: 'zmianas#create'
    
    get '/signup', to: 'users#new'
    get '/help', to: 'static_pages#help'
    get '/home', to: 'static_pages#home'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/kalendarz', to: 'kalendarz#new'
    get '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz', to: 'kalendarz#create'
    get 'nadgodzinies/new', to: 'nadgodzinies#new'
    get '/nadgodzinies', to: 'nadgodzinies#show'
    get '/users/nadgodzinies/new', to: 'nadgodzinies#new'
    
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end
#zmianas_path

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    before_action :get_user,   only: [:edit, :update]
    before_action :valid_user, only: [:edit, :update]
    before_action :check_expiration, only: [:edit, :update]

    def new
    end
    # Password reset action
    def create
        @user = User.find_by(email: params[:password_reset][:email].downcase)
        if @user
            @user.create_reset_digest
            @user.send_password_reset_email
            flash[:info] = "Email został wysłany z instrukcją resetowania chasła."
            redirect_to root_url
        else
            flash.now[:danger] = "Podany adres email nie znaleziony!"
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
    if params[:user][:password].empty?                  # Case (3)
      @user.errors.add(:password, "Chasło nie może być puste!")
      render 'edit'
    elsif @user.update_attributes(user_params)          # Case (4)
      log_in @user
      flash[:success] = "Chasło zostało zresetowane."
      redirect_to @user
    else
      render 'edit'                                     # Case (2)
    end
  end

    
    private
    
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end
    def check_expiration
        if @user.password_reset_expired?
            flash[:danger] = "Reset chasła wygasł!"
            redirect_to new_password_reset_url
        end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Resetowanie chasła') %>
<h1>Resetowanie chasła</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object  %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, 'nowe chasło' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Potwierdż nowe chasło" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Uaktualnij chasło", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Zapomniane chasło") %>
<h1>Zapomniane chasło</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Wyślij", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>