config/routes.rb
Rails.application.routes.draw do

  resources :nadgodzinies
  post 'zmianas/index', to: 'zmianas#index'
  post 'zmianas/show'
  get 'zmianas/new'
  get 'zmianas/create'
  get 'zmianas/show'
  get 'zmianas/index'
  delete '/zmianas/destroy', to: 'zmianas#destroy'
  get '/zmianas/delete/', to: 'zmianas#destroy'

      resources :users do
          member do
              get :following, :followers
          end
      end
    resources :relationships,       only: [:create, :destroy]
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    
    post '/zmianas/destroy', to: 'zmianas#destroy'
    post '/zmianas', to: 'zmianas#create'
    
    get '/signup', to: 'users#new'
    get '/help', to: 'static_pages#help'
    get '/home', to: 'static_pages#home'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/kalendarz', to: 'kalendarz#new'
    get '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz', to: 'kalendarz#create'
    get 'nadgodzinies/new', to: 'nadgodzinies#new'
    get '/nadgodzinies', to: 'nadgodzinies#show'
    get '/users/nadgodzinies/new', to: 'nadgodzinies#new'
    
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end
#zmianas_path

app/models/nadgodziny.rb
class Nadgodziny < ApplicationRecord
      validates :user, presence: true
end

app/controllers/nadgodzinies_controller.rb
class NadgodziniesController < ApplicationController
  before_action :set_nadgodziny, only: [:show, :edit, :update, :destroy]
  before_action :admin_user,     only: [:destroy, :show]
  # GET /nadgodzinies
  # GET /nadgodzinies.json
  def index
    @nadgodzinies = Nadgodziny.all
  end

  # GET /nadgodzinies/1
  # GET /nadgodzinies/1.json
  def show
  end

  # GET /nadgodzinies/new
  def new
      @user = current_user
      @nadgodziny = Nadgodziny.new
  end

  # GET /nadgodzinies/1/edit
  def edit
  end

  # POST /nadgodzinies
  # POST /nadgodzinies.json
  def create
    @nadgodziny = Nadgodziny.new(nadgodziny_params)

    respond_to do |format|
       
        if
                 @nadgodziny.save
        format.html { redirect_to root_path, notice: 'Zapisałeś się na nadgodziny.' }
        format.json { render :show, status: :created, location: @nadgodziny }
      else
        format.html { render :new }
        format.json { render json: @nadgodziny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nadgodzinies/1
  # PATCH/PUT /nadgodzinies/1.json
  def update
    respond_to do |format|
      if @nadgodziny.update(nadgodziny_params)
        format.html { redirect_to @nadgodziny, notice: 'Nadgodziny zostały zapisane.' }
        format.json { render :show, status: :ok, location: @nadgodziny }
      else
        format.html { render :edit }
        format.json { render json: @nadgodziny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nadgodzinies/1
  # DELETE /nadgodzinies/1.json
  def destroy
    @nadgodziny.destroy
    respond_to do |format|
      format.html { redirect_to nadgodzinies_url, notice: 'Zmieniłeś swoje nadgodziny.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nadgodziny
      @nadgodziny = Nadgodziny.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nadgodziny_params
      params.require(:nadgodziny).permit(:user, :data)
    end
end

app/helpers/nadgodzinies_helper.rb
module NadgodziniesHelper
end

app/views/nadgodzinies/_form.html.erb
<%= form_for(nadgodziny) do |f| %>
  <% if nadgodziny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nadgodziny.errors.count, "error") %> prohibited this nadgodziny from being saved:</h2>

      <ul>
      <% nadgodziny.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= "Obecny użytkowik #{current_user.name}" %>
    <%= f.hidden_field :user, :value => current_user.id %>

  <div class="field">
    <%= f.label :data %>
    <%= f.date_select :data %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nadgodzinies/edit.html.erb
<h1>Editing Nadgodziny</h1>

<%= render 'form', nadgodziny: @nadgodziny %>

<%= link_to 'Show', @nadgodziny %> |
<%= link_to 'Back', nadgodzinies_path %>

app/views/nadgodzinies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nadgodziny</h1>

<table>
  <thead>
    <tr>
      <th>User: </th>
      <th>Data:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nadgodzinies.each do |nadgodziny| %>
      <tr>
        <td><%= User.find(nadgodziny.user).name %></td>
        <td><%= nadgodziny.data %></td>
        <td><%= link_to 'Show', nadgodziny %></td>
        <td><%= link_to 'Edit', edit_nadgodziny_path(nadgodziny) %></td>
        <td><%= link_to 'Destroy', nadgodziny, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj nadgodziny', new_nadgodziny_path %>

app/views/nadgodzinies/new.html.erb
<h1>Zgłoś się na nadgodziny!</h1>

<%= render 'form', nadgodziny: @nadgodziny %>

<%= link_to 'Back', nadgodzinies_path %>

app/views/nadgodzinies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pracownik:</strong>
  <%= User.find(@nadgodziny.user).name %>
</p>

<p>
  <strong>Data:</strong>
  <%= @nadgodziny.data %>
</p>

<%= link_to 'Edit', edit_nadgodziny_path(@nadgodziny) %> |
<%= link_to 'Back', nadgodzinies_path %>