config/routes.rb
Rails.application.routes.draw do

  resources :nadgodzinies
  post 'zmianas/index', to: 'zmianas#index'
  post 'zmianas/show'
  get 'zmianas/new'
  get 'zmianas/create'
  get 'zmianas/show'
  get 'zmianas/index'
  delete '/zmianas/destroy', to: 'zmianas#destroy'
  get '/zmianas/delete/', to: 'zmianas#destroy'

      resources :users do
          member do
              get :following, :followers
          end
      end
    resources :relationships,       only: [:create, :destroy]
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    
    post '/zmianas/destroy', to: 'zmianas#destroy'
    post '/zmianas', to: 'zmianas#create'
    
    get '/signup', to: 'users#new'
    get '/help', to: 'static_pages#help'
    get '/home', to: 'static_pages#home'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/kalendarz', to: 'kalendarz#new'
    get '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz', to: 'kalendarz#create'
    get 'nadgodzinies/new', to: 'nadgodzinies#new'
    get '/nadgodzinies', to: 'nadgodzinies#show'
    get '/users/nadgodzinies/new', to: 'nadgodzinies#new'
    
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end
#zmianas_path

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Formularz zawiera <%= "#{object.errors.count} błędy!" %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_kalendarz.html.erb
<div class="container">
<div class="calendar-container">
<header>
  <div class="day">1</div>
  <div class="month">Grudzień</div>
  </header>
    <table class="calendar">
    <thead>
        <tr>
            <td>Pon</td><td>Wto</td><td>Śro</td><td>Czw</td><td>Pią</td><td>Sob</td><td>Nie</td>
        </tr>
    </thead>
    <tbody>
    <% @string = Zmiana.find(current_user.zmiana_id).kalendarz %>
    <% string = @string %>
    <% string.split('<tr>').each do |tydzien| %>
        <tr>
            <% tydzien.split.each do |dzien| %>
                <% tab = dzien.split('|') %>
                <% opcja = tab[1] %>
                <% d = tab[0] %>
                <td class="<%= opcja %>"><%= d %></td>
            <% end %>
        </tr>
    <% end %>
    </tbody>
    </table>
    <div class="ring-left"></div>
    <div class="ring-right"></div>
</div> <!-- end calendar-container -->
</div> <!-- end container -->

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Utworz", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "moj profil", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>