config/routes.rb
Rails.application.routes.draw do

  resources :nadgodzinies
  post 'zmianas/index', to: 'zmianas#index'
  post 'zmianas/show'
  get 'zmianas/new'
  get 'zmianas/create'
  get 'zmianas/show'
  get 'zmianas/index'
  delete '/zmianas/destroy', to: 'zmianas#destroy'
  get '/zmianas/delete/', to: 'zmianas#destroy'

      resources :users do
          member do
              get :following, :followers
          end
      end
    resources :relationships,       only: [:create, :destroy]
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    
    post '/zmianas/destroy', to: 'zmianas#destroy'
    post '/zmianas', to: 'zmianas#create'
    
    get '/signup', to: 'users#new'
    get '/help', to: 'static_pages#help'
    get '/home', to: 'static_pages#home'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/kalendarz', to: 'kalendarz#new'
    get '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz/new', to: 'kalendarz#new'
    post '/kalendarz', to: 'kalendarz#create'
    get 'nadgodzinies/new', to: 'nadgodzinies#new'
    get '/nadgodzinies', to: 'nadgodzinies#show'
    get '/users/nadgodzinies/new', to: 'nadgodzinies#new'
    
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end
#zmianas_path

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "O...", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Nowości</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Grafik", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Domowa", root_path %></li>
        <li><%= link_to "Pomoc", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Użytkownicy", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Konto <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li><%= link_to "Ustawienia", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Zgłoś się na nadgodziny", 'nadgodzinies/new' %></li>
              <li class="divider"></li>
              <li>
              <% if logged_in? && current_user.admin? %>
          <%= link_to "Nadgodziny", '/nadgodzinies' %>
          <% end %>
          </li>
          <li>
                <%= link_to "Wyloguj", logout_path, method: 'delete' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Zaloguj", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header1.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Administarcja", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Domowa", root_path %></li>
        <li><%= link_to "Pomoc", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Użytkownicy", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Konto <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li><%= link_to "Ustawienia", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Wyloguj", logout_path, method: 'delete' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Zaloguj", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>